# -*- coding: utf-8 -*-
"""suggestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHYT1P4IJrL782h107DrSatkb1xUo7pC
"""
import streamlit as st
import joblib
import pandas as pd
from PIL import Image
import requests
from io import BytesIO

# Try-Except for plotting libraries to prevent crashes if requirements.txt isn't updated yet
try:
    import matplotlib.pyplot as plt
    import seaborn as sns
    PLOT_AVAILABLE = True
except ImportError:
    PLOT_AVAILABLE = False

# 1. PAGE CONFIG
st.set_page_config(page_title="Dublin StaySelect", page_icon="🍀", layout="wide")

# 2. CUSTOM CSS
st.markdown("""
    <style>
    .main { background-color: #f8f9fa; }
    div[data-testid="stMetricValue"] { color: #FF5A5F; }
    .stButton>button { width: 100%; border-radius: 20px; height: 3em; background-color: #FF5A5F; color: white; border: none; }
    .stButton>button:hover { background-color: #de3e44; color: white; }
    </style>
    """, unsafe_allow_html=True)

# 3. DATA LOADING
@st.cache_data
def load_data():
    return pd.read_csv('dublin_merged_df(1).csv.gz', compression='gzip')

@st.cache_resource
def load_suggestion_model():
    return joblib.load('recommendation_system/baseline_model.pkl')

def get_image(url):
    try:
        response = requests.get(url, timeout=5)
        return Image.open(BytesIO(response.content))
    except Exception:
        return None

# 4. RECOMMENDATION LOGIC
def recommend_airbnbs(user_id, listings_df, final_model):
    try:
        all_listings = listings_df['id_x'].unique()
        user_listings = listings_df[listings_df['reviewer_id'] == user_id]['id_x'].unique()
        listings_to_predict = list(set(all_listings) - set(user_listings))
        
        user_listing_pairs = [(user_id, lid, 0) for lid in listings_to_predict]
        predictions = final_model.test(user_listing_pairs)
        top_recs = sorted(predictions, key=lambda x: x.est, reverse=True)[:5]

        st.subheader(f"✨ Top Matches for Guest {user_id}")
        
        for idx, rec in enumerate(top_recs, 1):
            listing = listings_df[listings_df['id_x'] == rec.iid].iloc[0]
            with st.container():
                col1, col2 = st.columns([1, 2])
                with col1:
                    img = get_image(listing['picture_url'])
                    if img:
                        st.image(img, use_column_width=True)
                    else:
                        st.info("No Preview Image Available")
                with col2:
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Nightly Rate", f"€{listing['price']}")
                    m2.metric("Capacity", f"{int(listing['accommodates'])} Guests")
                    m3.metric("Beds", f"{int(listing['bedrooms'])}")
                    with st.expander("Explore Property Details"):
                        st.write(listing['description'])
                        st.markdown(f"**Neighborhood:** {listing['neighbourhood']}")
                    st.link_button("🔗 View Official Listing", listing['listing_url'])
                st.divider()
    except Exception as e:
        st.error(f"Error generating recommendations: {e}")

# 5. MAIN INTERFACE
def main():
    raw_df = load_data()
    final_model = load_suggestion_model()

    # Sidebar: Simplified for navigation
    with st.sidebar:
        st.title("🍀 DublinStay")
        st.markdown("---")
        top_ids = raw_df['reviewer_id'].value_counts().head(5).index.tolist()
        selected_id = st.selectbox("Quick Test Profiles:", top_ids)
        st.info("Select a User ID to see personalized Dublin recommendations.")

    # Main Tabs
    tab1, tab2, tab3 = st.tabs(["🔍 Find Stays", "📊 Model Performance", "⚖️ Limitations"])

    with tab1:
        st.title("Personalized Dublin Stays")
        st.markdown("Discover accommodations tailored to your past preferences in Dublin.")
        user_input = st.number_input("User ID:", value=int(selected_id))
        if st.button("Generate Recommendations"):
            with st.spinner('Analyzing Dublin rentals...'):
                recommend_airbnbs(user_input, raw_df, final_model)

    with tab2:
        st.header("Model Evaluation & Scale")
        
        # Performance Metrics
        col_m1, col_m2, col_m3 = st.columns(3)
        col_m1.metric("Training Samples", "276,126")
        col_m2.metric("RMSE", "0.4347")
        col_m3.metric("MAE", "0.3205")
        
        st.markdown("---")
        
        # Sentiment Distribution
        if PLOT_AVAILABLE:
            st.subheader("📈 Training Data Distribution")
            st.write("This chart shows the sentiment scores (compound_scores) used to train the BaselineOnly model.")
            fig, ax = plt.subplots(figsize=(10, 4))
            sns.histplot(raw_df['compound_scores'], kde=True, ax=ax, color="#FF5A5F")
            ax.set_title("Frequency of Sentiment Scores in Dublin Reviews")
            st.pyplot(fig)
        else:
            st.warning("Visualization libraries (Matplotlib/Seaborn) not yet loaded. Check requirements.txt.")

    with tab3:
        st.header("Project Considerations")
        col_left, col_right = st.columns(2)
        with col_left:
            st.subheader("⚠️ Technical Limitations")
            st.write(f"""
            - **Positivity Bias:** Highly skewed data (0.8+) makes distinguishing high-quality stays a challenge.
            - **Cold Start:** The system requires existing review history to make accurate matches.
            """)
        
        #with col_right:
            #st.subheader("🛡️ Ethical Considerations")
            #st.write("""
            #- **Fairness:** Relying on sentiment can favor hosts who are "polite" over those who offer better value.
            #- **Market Impact:** Algorithmic bias may concentrate tourism in specific Dublin neighborhoods.
            #- **Data Privacy:** User history is used anonymously to protect individual identities.
            #""")
        
        st.warning("Note: Recommendations are based on historical sentiment and may not reflect current conditions.")

if __name__ == "__main__":
    main()
